# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1441620981);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1441621101);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1441627821);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1441620861);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1441620741);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 266240);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.download.lastDir", "/home/init_user/Downloads");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 22);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150711004644");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20150711004644");
user_pref("browser.startup.homepage_override.mstone", "31.7.0");
user_pref("browser.syncPromoViewsLeftMap", "{\"passwords\":0}");
user_pref("datareporting.healthreport.lastDataSubmissionRequestedTime", "1442225662556");
user_pref("datareporting.healthreport.lastDataSubmissionSuccessfulTime", "1442225663751");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1442312063751");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAccepted", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1441313906481");
user_pref("datareporting.policy.dataSubmissionPolicyResponseTime", "1441342739743");
user_pref("datareporting.policy.dataSubmissionPolicyResponseType", "accepted-implicit-time-elapsed");
user_pref("datareporting.policy.firstRunTime", "1436546867667");
user_pref("datareporting.sessions.current.activeTicks", 12);
user_pref("datareporting.sessions.current.firstPaint", 2611);
user_pref("datareporting.sessions.current.main", 909);
user_pref("datareporting.sessions.current.sessionRestored", 2748);
user_pref("datareporting.sessions.current.startTime", "1442225597769");
user_pref("datareporting.sessions.current.totalTime", 63);
user_pref("datareporting.sessions.currentIndex", 29);
user_pref("datareporting.sessions.prunedIndex", 28);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_INSPECTOR_OPENED_PER_USER_FLAG\":\"31.7.0\",\"DEVTOOLS_RULEVIEW_OPENED_PER_USER_FLAG\":\"31.7.0\"}");
user_pref("devtools.toolbox.selectedTool", "inspector");
user_pref("devtools.toolsidebar-width.inspector", 0);
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountTotal", 15);
user_pref("extensions.blocklist.pingCountVersion", 15);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:31.7.0");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib64/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1436540744000,\"rdfTime\":1436540728000}}}]");
user_pref("extensions.lastAppVersion", "31.7.0");
user_pref("extensions.lastPlatformVersion", "31.7.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20150711004644");
user_pref("gecko.mstone", "31.7.0");
user_pref("idle.lastDailyNotification", 1442225713);
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1442225662);
user_pref("places.history.expiration.transient_current_max_pages", 21993);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1440615677);
user_pref("toolkit.startup.last_success", 1442225598);
user_pref("toolkit.telemetry.previousBuildID", "20150711004644");
